os: linux
language: cpp
compiler: gcc
dist: trusty
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip3 install requests
# command to run tests
env:
  global:
    - DEPLOY_TAG_FEATURE=deploy/feature
    - DEPLOY_TAG_DEV=deploy/dev
    - DEPLOY_TAG_STABLE=deploy/stable
addons:
  sonarcloud:
    organization: "szefoski" # the key of the org you chose at step #3
    token: ${SONAR_TOKEN}
script:
    - build-wrapper-linux-x86-64 --out-dir bw-output make
    - ls
    - ls bin
    - ls bw-output
    - echo $TRAVIS_TAG
before_deploy:
    - curl https://raw.githubusercontent.com/szefoski/githubhoping/cd538b435785a3e827642440312824b62726e1d2/githubhoping.py --output githubhoping.py
    - python3 ./githubhoping.py szefoski ci-travis-test $TRAVIS_TAG ${GITHUB_TOKEN}
deploy:
  provider: releases
  token: ${GITHUB_TOKEN}
  file: ./bin/program2
  skip_cleanup: true
  overwrite: true
  name: Jakis tytul
  body: date
  on:
    tags: true
    condition: $TRAVIS_TAG == "$DEPLOY_TAG_FEATURE" || $TRAVIS_TAG == "$DEPLOY_TAG_DEV" || $TRAVIS_TAG == "$DEPLOY_TAG_STABLE"
